#pragma once

#include "src/utils/export.hpp"
#include "src/interop.hpp"

DLL_EXPORT void Player_Kick(IEntity* player);
DLL_EXPORT void Player_Ban(IEntity* player, const char* reason = "");
DLL_EXPORT bool Player_IsBot(const IEntity* player);
DLL_EXPORT const PeerNetworkData Player_GetNetworkData(const IEntity* player);
DLL_EXPORT unsigned Player_GetPing(const IEntity* player);
DLL_EXPORT bool Player_SendPacket(IEntity* player, Span<uint8_t> data, int channel, bool dispatchEvents = true);
DLL_EXPORT bool Player_SendRPC(IEntity* player, int id, Span<uint8_t> data, int channel, bool dispatchEvents = true);
DLL_EXPORT void Player_BroadcastRPCToStreamed(IEntity* player, int id, Span<uint8_t> data, int channel, bool skipFrom = false);
DLL_EXPORT void Player_BroadcastPacketToStreamed(IEntity* player, Span<uint8_t> data, int channel, bool skipFrom = true);
DLL_EXPORT void Player_BroadcastSyncPacket(IEntity* player, Span<uint8_t> data, int channel);
DLL_EXPORT void Player_Spawn(IEntity* player);
DLL_EXPORT ClientVersion Player_GetClientVersion(const IEntity* player);
DLL_EXPORT const char* Player_GetClientVersionName(const IEntity* player);
DLL_EXPORT void Player_SetPositionFindZ(IEntity* player, Vector3 pos);
DLL_EXPORT void Player_SetCameraPosition(IEntity* player, Vector3 pos);
DLL_EXPORT Vector3 Player_GetCameraPosition(IEntity* player);
DLL_EXPORT void Player_SetCameraLookAt(IEntity* player, Vector3 pos, PlayerCameraCutType cutType);
DLL_EXPORT Vector3 Player_GetCameraLookAt(IEntity* player);
DLL_EXPORT void Player_SetCameraBehind(IEntity* player);
DLL_EXPORT void Player_InterpolateCameraPosition(IEntity* player, Vector3 from, Vector3 to, int time, PlayerCameraCutType cutType);
DLL_EXPORT void Player_InterpolateCameraLookAt(IEntity* player, Vector3 from, Vector3 to, int time, PlayerCameraCutType cutType);
DLL_EXPORT void Player_AttachCameraToObject(IEntity* player, IEntity* object);
DLL_EXPORT void Player_AttachCameraToPlayerObject(IEntity* player, IEntity* playerObject);
DLL_EXPORT EPlayerNameStatus Player_SetName(IEntity* player, const char* name);
DLL_EXPORT const char* Player_GetName(const IEntity* player);
DLL_EXPORT const char* Player_GetSerial(const IEntity* player);
DLL_EXPORT void Player_GiveWeapon(IEntity* player, WeaponSlotData weapon);
DLL_EXPORT void Player_RemoveWeapon(IEntity* player, uint8_t weapon);
DLL_EXPORT void Player_SetWeaponAmmo(IEntity* player, WeaponSlotData data);
DLL_EXPORT const WeaponSlotData* Player_GetWeapons(const IEntity* player);
DLL_EXPORT CWeaponSlotData Player_GetWeaponSlot(IEntity* player, int slot);
DLL_EXPORT void Player_ResetWeapons(IEntity* player);
DLL_EXPORT void Player_SetArmedWeapon(IEntity* player, uint32_t weapon);
DLL_EXPORT uint32_t Player_GetArmedWeapon(const IEntity* player);
DLL_EXPORT uint32_t Player_GetArmedWeaponAmmo(const IEntity* player);
DLL_EXPORT void Player_SetShopName(IEntity* player, const char* name);
DLL_EXPORT const char* Player_GetShopName(const IEntity* player);
DLL_EXPORT void Player_SetDrunkLevel(IEntity* player, int level);
DLL_EXPORT int Player_GetDrunkLevel(const IEntity* player);
DLL_EXPORT void Player_SetColour(IEntity* player, const Colour& colour);
DLL_EXPORT Colour Player_GetColour(const IEntity* player);
DLL_EXPORT void Player_SetOtherColour(IEntity* player, IEntity* other, const Colour& colour);
DLL_EXPORT bool Player_GetOtherColour(const IEntity* player, IEntity* other, Colour* colour);
DLL_EXPORT void Player_SetControllable(IEntity* player, bool controllable);
DLL_EXPORT bool Player_GetControllable(const IEntity* player);
DLL_EXPORT void Player_SetSpectating(IEntity* player, bool spectating);
DLL_EXPORT void Player_SetWantedLevel(IEntity* player, unsigned level);
DLL_EXPORT unsigned Player_GetWantedLevel(const IEntity* player);
DLL_EXPORT void Player_PlaySound(IEntity* player, uint32_t sound, Vector3 pos);
DLL_EXPORT uint32_t Player_LastPlayedSound(const IEntity* player);
DLL_EXPORT void Player_PlayAudio(IEntity* player, const char* url, bool usePos = false, Vector3 pos = Vector3(0.f), float distance = 0.f);
DLL_EXPORT bool Player_PlayerCrimeReport(IEntity* player, IEntity* suspect, int crime);
DLL_EXPORT void Player_StopAudio(IEntity* player);
DLL_EXPORT const char* Player_LastPlayedAudio(const IEntity* player);
DLL_EXPORT void Player_CreateExplosion(IEntity* player, Vector3 vec, int type, float radius);
DLL_EXPORT void Player_SendDeathMessage(IEntity* player, IEntity* killed, IEntity* killer, int weapon);
DLL_EXPORT void Player_SendEmptyDeathMessage(IEntity* player);
DLL_EXPORT void Player_RemoveDefaultObjects(IEntity* player, unsigned model, Vector3 pos, float radius);
DLL_EXPORT void Player_ForceClassSelection(IEntity* player);
DLL_EXPORT void Player_SetMoney(IEntity* player, int money);
DLL_EXPORT void Player_GiveMoney(IEntity* player, int money);
DLL_EXPORT void Player_ResetMoney(IEntity* player);
DLL_EXPORT int Player_GetMoney(IEntity* player);
DLL_EXPORT void Player_SetMapIcon(IEntity* player, int id, Vector3 pos, int type, const Colour& colour, MapIconStyle style);
DLL_EXPORT void Player_UnsetMapIcon(IEntity* player, int id);
DLL_EXPORT void Player_UseStuntBonuses(IEntity* player, bool enable);
DLL_EXPORT void Player_ToggleOtherNameTag(IEntity* player, IEntity* other, bool toggle);
DLL_EXPORT void Player_SetTime(IEntity* player, Hours hr, Minutes min);
DLL_EXPORT void Player_GetTime(const IEntity* player, int64_t* hours, int64_t* minutes);
DLL_EXPORT void Player_UseClock(IEntity* player, bool enable);
DLL_EXPORT bool Player_HasClock(const IEntity* player);
DLL_EXPORT void Player_UseWidescreen(IEntity* player, bool enable);
DLL_EXPORT bool Player_HasWidescreen(const IEntity* player);
DLL_EXPORT void Player_SetTransform(IEntity* player, Vector3 vec3);
DLL_EXPORT void Player_SetHealth(IEntity* player, float health);
DLL_EXPORT float Player_GetHealth(const IEntity* player);
DLL_EXPORT void Player_SetScore(IEntity* player, int score);
DLL_EXPORT int Player_GetScore(const IEntity* player);
DLL_EXPORT void Player_SetArmour(IEntity* player, float armour);
DLL_EXPORT float Player_GetArmour(const IEntity* player);
DLL_EXPORT void Player_SetGravity(IEntity* player, float gravity);
DLL_EXPORT float Player_GetGravity(const IEntity* player);
DLL_EXPORT void Player_SetWorldTime(IEntity* player, Hours time);
DLL_EXPORT void Player_ApplyAnimation(IEntity* player, const AnimationData& animation, PlayerAnimationSyncType syncType);
DLL_EXPORT void Player_ClearAnimations(IEntity* player, PlayerAnimationSyncType syncType);
DLL_EXPORT PlayerAnimationData Player_GetAnimationData(const IEntity* player);
DLL_EXPORT PlayerSurfingData Player_GetSurfingData(const IEntity* player);
DLL_EXPORT void Player_StreamInForPlayer(IEntity* player, const IEntity* other);
DLL_EXPORT bool Player_IsStreamedInForPlayer(const IEntity* player, const IEntity* other);
DLL_EXPORT void Player_StreamOutForPlayer(IEntity* player, const IEntity* other);
DLL_EXPORT std::size_t Player_GetStreamedPlayers(const IEntity* player, IEntity* streamPlayers);
DLL_EXPORT PlayerState Player_GetState(const IEntity* player);
DLL_EXPORT void Player_SetTeam(IEntity* player, int team);
DLL_EXPORT int Player_GetTeam(const IEntity* player);
DLL_EXPORT void Player_SetSkin(IEntity* player, int skin, bool send = true);
DLL_EXPORT int Player_GetSkin(const IEntity* player);
DLL_EXPORT void Player_SetChatBubble(IEntity* player, const char* text, const Colour& colour, float drawDist, int64_t expireMs);
DLL_EXPORT void Player_SendClientMessage(IEntity* player, const Colour& colour, const char* message);
DLL_EXPORT void Player_SendChatMessage(IEntity* player, IEntity* sender, const char* message);
DLL_EXPORT void Player_SendCommand(IEntity* player, const char* message);
DLL_EXPORT void Player_SendGameText(IEntity* player, const char* message, int64_t timeMs, int style);
DLL_EXPORT void Player_HideGameText(IEntity* player, int style);
DLL_EXPORT bool Player_HasGameText(const IEntity* player, int style);
DLL_EXPORT bool Player_GetGameText(const IEntity* player, int style, char* message, std::size_t size, int64_t* time, int64_t* remaining); // both are milliseconds
DLL_EXPORT void Player_SetWeather(IEntity* player, int weatherID);
DLL_EXPORT int Player_GetWeather(const IEntity* player);
DLL_EXPORT void Player_SetWorldBounds(IEntity* player, Vector4 coords);
DLL_EXPORT Vector4 Player_GetWorldBounds(const IEntity* player);
DLL_EXPORT void Player_SetFightingStyle(IEntity* player, PlayerFightingStyle style);
DLL_EXPORT PlayerFightingStyle Player_GetFightingStyle(const IEntity* player);
DLL_EXPORT void Player_SetSkillLevel(IEntity* player, PlayerWeaponSkill skill, int level);
DLL_EXPORT void Player_SetAction(IEntity* player, PlayerSpecialAction action);
DLL_EXPORT PlayerSpecialAction Player_GetAction(const IEntity* player);
DLL_EXPORT void Player_SetVelocity(IEntity* player, Vector3 velocity);
DLL_EXPORT Vector3 Player_GetVelocity(const IEntity* player);
DLL_EXPORT void Player_SetInterior(IEntity* player, unsigned interior);
DLL_EXPORT unsigned Player_GetInterior(const IEntity* player);
DLL_EXPORT const PlayerKeyData Player_GetKeyData(const IEntity* player);
DLL_EXPORT const uint16_t* Player_GetSkillLevels(const IEntity* player);
DLL_EXPORT const PlayerAimData Player_GetAimData(const IEntity* player);
DLL_EXPORT const PlayerBulletData Player_GetBulletData(const IEntity* player);
DLL_EXPORT void Player_UseCameraTargeting(IEntity* player, bool enable);
DLL_EXPORT bool Player_HasCameraTargeting(const IEntity* player);
DLL_EXPORT void Player_RemoveFromVehicle(IEntity* player, bool force);
DLL_EXPORT IEntity* Player_GetCameraTargetPlayer(IEntity* player);
DLL_EXPORT IVehicle* Player_GetCameraTargetVehicle(IEntity* player);
DLL_EXPORT IObject* Player_GetCameraTargetObject(IEntity* player);
DLL_EXPORT IActor* Player_GetCameraTargetActor(IEntity* player);
DLL_EXPORT IEntity* Player_GetTargetPlayer(IEntity* player);
DLL_EXPORT IActor* Player_GetTargetActor(IEntity* player);
DLL_EXPORT void Player_SetRemoteVehicleCollisions(IEntity* player, bool collide);
DLL_EXPORT void Player_SpectatePlayer(IEntity* player, IEntity* target, PlayerSpectateMode mode);
DLL_EXPORT void Player_SpectateVehicle(IEntity* player, IVehicle* target, PlayerSpectateMode mode);
DLL_EXPORT const PlayerSpectateData Player_GetSpectateData(const IEntity* player);
DLL_EXPORT void Player_SendClientCheck(IEntity* player, int actionType, int address, int offset, int count);
DLL_EXPORT void Player_ToggleGhostMode(IEntity* player, bool toggle);
DLL_EXPORT bool Player_IsGhostModeEnabled(const IEntity* player);
DLL_EXPORT int Player_GetDefaultObjectsRemoved(const IEntity* player);
DLL_EXPORT bool Player_GetKickStatus(const IEntity* player);
DLL_EXPORT void Player_ClearTasks(IEntity* player, PlayerAnimationSyncType syncType);
DLL_EXPORT void Player_AllowWeapons(IEntity* player, bool allow);
DLL_EXPORT bool Player_AreWeaponsAllowed(const IEntity* player);
DLL_EXPORT void Player_AllowTeleport(IEntity* player, bool allow);
DLL_EXPORT bool Player_IsTeleportAllowed(const IEntity* player);
DLL_EXPORT bool Player_IsUsingOfficialClient(const IEntity* player);
