#pragma once

#include "anim.hpp"
#include "entity.hpp"
#include "gtaquat.hpp"
#include "player.hpp"
#include "types.hpp"
#include "src/utils/export.hpp"

DLL_EXPORT void Player_Kick(const IPlayer* player);
DLL_EXPORT void Player_Ban(const IPlayer* player, const char* reason = "");
DLL_EXPORT bool Player_IsBot(const IPlayer* player);
DLL_EXPORT const PeerNetworkData Player_GetNetworkData(const IPlayer* player);
DLL_EXPORT unsigned Player_GetPing(const IPlayer* player);
DLL_EXPORT bool Player_SendPacket(const IPlayer* player, Span<uint8_t> data, int channel, bool dispatchEvents = true);
DLL_EXPORT bool Player_SendRPC(const IPlayer* player, int id, Span<uint8_t> data, int channel, bool dispatchEvents = true);
DLL_EXPORT void Player_BroadcastRPCToStreamed(const IPlayer* player, int id, Span<uint8_t> data, int channel, bool skipFrom = false);
DLL_EXPORT void Player_BroadcastPacketToStreamed(const IPlayer* player, Span<uint8_t> data, int channel, bool skipFrom = true);
DLL_EXPORT void Player_BroadcastSyncPacket(const IPlayer* player, Span<uint8_t> data, int channel);
DLL_EXPORT void Player_Spawn(const IPlayer* player);
DLL_EXPORT ClientVersion Player_GetClientVersion(const IPlayer* player);
DLL_EXPORT const char* Player_GetClientVersionName(const IPlayer* player);
DLL_EXPORT void Player_SetPositionFindZ(const IPlayer* player, Vector3 pos);
DLL_EXPORT void Player_SetCameraPosition(const IPlayer* player, Vector3 pos);
DLL_EXPORT Vector3 Player_GetCameraPosition(const IPlayer* player);
DLL_EXPORT void Player_SetCameraLookAt(const IPlayer* player, Vector3 pos, int cutType);
DLL_EXPORT Vector3 Player_GetCameraLookAt(const IPlayer* player);
DLL_EXPORT void Player_SetCameraBehind(const IPlayer* player);
DLL_EXPORT void Player_InterpolateCameraPosition(const IPlayer* player, Vector3 from, Vector3 to, int time, PlayerCameraCutType cutType);
DLL_EXPORT void Player_InterpolateCameraLookAt(const IPlayer* player, Vector3 from, Vector3 to, int time, PlayerCameraCutType cutType);
DLL_EXPORT void Player_AttachCameraToObject(const IPlayer* player, const IObject* object);
DLL_EXPORT void Player_AttachCameraToPlayerObject(const IPlayer* player, const IPlayerObject* object);
DLL_EXPORT EPlayerNameStatus Player_SetName(const IPlayer* player, const char* name);
DLL_EXPORT const char* Player_GetName(const IPlayer* player);
DLL_EXPORT const char* Player_GetSerial(const IPlayer* player);
DLL_EXPORT void Player_GiveWeapon(const IPlayer* player, WeaponSlotData weapon);
DLL_EXPORT void Player_RemoveWeapon(const IPlayer* player, uint8_t weapon);
DLL_EXPORT void Player_SetWeaponAmmo(const IPlayer* player, WeaponSlotData data);
DLL_EXPORT std::size_t Player_GetWeapons(const IPlayer* player, WeaponSlots* slots);
DLL_EXPORT void Player_GetWeaponSlot(const IPlayer* player, int slot, WeaponSlotData* data);
DLL_EXPORT void Player_ResetWeapons(const IPlayer* player);
DLL_EXPORT void Player_SetArmedWeapon(const IPlayer* player, uint32_t weapon);
DLL_EXPORT uint32_t Player_GetArmedWeapon(const IPlayer* player);
DLL_EXPORT uint32_t Player_GetArmedWeaponAmmo(const IPlayer* player);
DLL_EXPORT void Player_SetShopName(const IPlayer* player, const char* name);
DLL_EXPORT const char* Player_GetShopName(const IPlayer* player);
DLL_EXPORT void Player_SetDrunkLevel(const IPlayer* player, int level);
DLL_EXPORT int Player_GetDrunkLevel(const IPlayer* player);
DLL_EXPORT void Player_SetColour(const IPlayer* player, const Colour& colour);
DLL_EXPORT const Colour Player_GetColour(const IPlayer* player);
DLL_EXPORT void Player_SetOtherColour(const IPlayer* player, const IPlayer* other, const Colour& colour);
DLL_EXPORT bool Player_GetOtherColour(const IPlayer* player, const IPlayer* other, Colour* colour);
DLL_EXPORT void Player_SetControllable(const IPlayer* player, bool controllable);
DLL_EXPORT bool Player_GetControllable(const IPlayer* player);
DLL_EXPORT void Player_SetSpectating(const IPlayer* player, bool spectating);
DLL_EXPORT void Player_SetWantedLevel(const IPlayer* player, unsigned level);
DLL_EXPORT unsigned Player_GetWantedLevel(const IPlayer* player);
DLL_EXPORT void Player_PlaySound(const IPlayer* player, uint32_t sound, Vector3 pos);
DLL_EXPORT uint32_t Player_LastPlayedSound(const IPlayer* player);
DLL_EXPORT void Player_PlayAudio(const IPlayer* player, const char* url, bool usePos = false, Vector3 pos = Vector3(0.f), float distance = 0.f);
DLL_EXPORT bool Player_PlayerCrimeReport(const IPlayer* player, const IPlayer* suspect, int crime);
DLL_EXPORT void Player_StopAudio(const IPlayer* player);
DLL_EXPORT const char* Player_LastPlayedAudio(const IPlayer* player);
DLL_EXPORT void Player_CreateExplosion(const IPlayer* player, Vector3 vec, int type, float radius);
DLL_EXPORT void Player_SendDeathMessage(const IPlayer* player, const IPlayer* killed, IPlayer* killer, int weapon);
DLL_EXPORT void Player_SendEmptyDeathMessage(const IPlayer* player);
DLL_EXPORT void Player_RemoveDefaultObjects(const IPlayer* player, unsigned model, Vector3 pos, float radius);
DLL_EXPORT void Player_ForceClassSelection(const IPlayer* player);
DLL_EXPORT void Player_SetMoney(const IPlayer* player, int money);
DLL_EXPORT void Player_GiveMoney(const IPlayer* player, int money);
DLL_EXPORT void Player_ResetMoney(const IPlayer* player);
DLL_EXPORT int Player_GetMoney(const IPlayer* player);
DLL_EXPORT void Player_SetMapIcon(const IPlayer* player, int id, Vector3 pos, int type, const Colour& colour, MapIconStyle style);
DLL_EXPORT void Player_UnsetMapIcon(const IPlayer* player, int id);
DLL_EXPORT void Player_UseStuntBonuses(const IPlayer* player, bool enable);
DLL_EXPORT void Player_ToggleOtherNameTag(const IPlayer* player, const IPlayer* other, bool toggle);
DLL_EXPORT void Player_SetTime(const IPlayer* player, Hours hr, Minutes min);
DLL_EXPORT void Player_GetTime(const IPlayer* player, int64_t* hours, int64_t* minutes);
DLL_EXPORT void Player_UseClock(const IPlayer* player, bool enable);
DLL_EXPORT bool Player_HasClock(const IPlayer* player);
DLL_EXPORT void Player_UseWidescreen(const IPlayer* player, bool enable);
DLL_EXPORT bool Player_HasWidescreen(const IPlayer* player);
DLL_EXPORT void Player_SetTransform(const IPlayer* player, GTAQuat tm);
DLL_EXPORT void Player_SetHealth(const IPlayer* player, float health);
DLL_EXPORT float Player_GetHealth(const IPlayer* player);
DLL_EXPORT void Player_SetScore(const IPlayer* player, int score);
DLL_EXPORT int Player_GetScore(const IPlayer* player);
DLL_EXPORT void Player_SetArmour(const IPlayer* player, float armour);
DLL_EXPORT float Player_GetArmour(const IPlayer* player);
DLL_EXPORT void Player_SetGravity(const IPlayer* player, float gravity);
DLL_EXPORT float Player_GetGravity(const IPlayer* player);
DLL_EXPORT void Player_SetWorldTime(const IPlayer* player, Hours time);
DLL_EXPORT void Player_ApplyAnimation(const IPlayer* player, const AnimationData& animation, PlayerAnimationSyncType syncType);
DLL_EXPORT void Player_ClearAnimations(const IPlayer* player, PlayerAnimationSyncType syncType);
DLL_EXPORT PlayerAnimationData Player_GetAnimationData(const IPlayer* player);
DLL_EXPORT PlayerSurfingData Player_GetSurfingData(const IPlayer* player);
DLL_EXPORT void Player_StreamInForPlayer(const IPlayer* player, const IPlayer* other);
DLL_EXPORT bool Player_IsStreamedInForPlayer(const IPlayer* player, const IPlayer* other);
DLL_EXPORT void Player_StreamOutForPlayer(const IPlayer* player, const IPlayer* other);
DLL_EXPORT std::size_t Player_GetStreamedPlayers(const IPlayer* player, IPlayer* streamPlayers);
DLL_EXPORT PlayerState Player_GetState(const IPlayer* player);
DLL_EXPORT void Player_SetTeam(const IPlayer* player, int team);
DLL_EXPORT int Player_GetTeam(const IPlayer* player);
DLL_EXPORT void Player_SetSkin(const IPlayer* player, int skin, bool send = true);
DLL_EXPORT int Player_GetSkin(const IPlayer* player);
DLL_EXPORT void Player_SetChatBubble(const IPlayer* player, const char* text, const Colour& colour, float drawDist, Milliseconds expire);
DLL_EXPORT void Player_SendClientMessage(const IPlayer* player, const Colour& colour, const char* message);
DLL_EXPORT void Player_SendChatMessage(const IPlayer* player, const IPlayer* sender, const char* message);
DLL_EXPORT void Player_SendCommand(const IPlayer* player, const char* message);
DLL_EXPORT void Player_SendGameText(const IPlayer* player, const char* message, Milliseconds time, int style);
DLL_EXPORT void Player_HideGameText(const IPlayer* player, int style);
DLL_EXPORT bool Player_HasGameText(const IPlayer* player, int style);
DLL_EXPORT bool Player_GetGameText(const IPlayer* player, int style, char* message, int64_t* time, int64_t* remaining); // both are milliseconds
DLL_EXPORT void Player_SetWeather(const IPlayer* player, int weatherID);
DLL_EXPORT int Player_GetWeather(const IPlayer* player);
DLL_EXPORT void Player_SetWorldBounds(const IPlayer* player, Vector4 coords);
DLL_EXPORT Vector4 Player_GetWorldBounds(const IPlayer* player);
DLL_EXPORT void Player_SetFightingStyle(const IPlayer* player, PlayerFightingStyle style);
DLL_EXPORT PlayerFightingStyle Player_GetFightingStyle(const IPlayer* player);
DLL_EXPORT void Player_SetSkillLevel(const IPlayer* player, PlayerWeaponSkill skill, int level);
DLL_EXPORT void Player_SetAction(const IPlayer* player, PlayerSpecialAction action);
DLL_EXPORT PlayerSpecialAction Player_GetAction(const IPlayer* player);
DLL_EXPORT void Player_SetVelocity(const IPlayer* player, Vector3 velocity);
DLL_EXPORT Vector3 Player_GetVelocity(const IPlayer* player);
DLL_EXPORT void Player_SetInterior(const IPlayer* player, unsigned interior);
DLL_EXPORT unsigned Player_GetInterior(const IPlayer* player);
DLL_EXPORT const PlayerKeyData Player_GetKeyData(const IPlayer* player);
DLL_EXPORT std::size_t Player_GetSkillLevels(const IPlayer* player, uint16_t* levels);
DLL_EXPORT const PlayerAimData Player_GetAimData(const IPlayer* player);
DLL_EXPORT const PlayerBulletData Player_GetBulletData(const IPlayer* player);
DLL_EXPORT void Player_UseCameraTargeting(const IPlayer* player, bool enable);
DLL_EXPORT bool Player_HasCameraTargeting(const IPlayer* player);
DLL_EXPORT void Player_RemoveFromVehicle(const IPlayer* player, bool force);
DLL_EXPORT IPlayer* Player_GetCameraTargetPlayer(const IPlayer* player);
DLL_EXPORT IVehicle* Player_GetCameraTargetVehicle(const IPlayer* player);
DLL_EXPORT IObject* Player_GetCameraTargetObject(const IPlayer* player);
DLL_EXPORT IActor* Player_GetCameraTargetActor(const IPlayer* player);
DLL_EXPORT IPlayer* Player_GetTargetPlayer(const IPlayer* player);
DLL_EXPORT IActor* Player_GetTargetActor(const IPlayer* player);
DLL_EXPORT void Player_SetRemoteVehicleCollisions(const IPlayer* player, bool collide);
DLL_EXPORT void Player_SpectatePlayer(const IPlayer* player, const IPlayer* target, PlayerSpectateMode mode);
DLL_EXPORT void Player_SpectateVehicle(const IPlayer* player, const IVehicle* target, PlayerSpectateMode mode);
DLL_EXPORT const PlayerSpectateData Player_GetSpectateData(const IPlayer* player);
DLL_EXPORT void Player_SendClientCheck(const IPlayer* player, int actionType, int address, int offset, int count);
DLL_EXPORT void Player_ToggleGhostMode(const IPlayer* player, bool toggle);
DLL_EXPORT bool Player_IsGhostModeEnabled(const IPlayer* player);
DLL_EXPORT int Player_GetDefaultObjectsRemoved(const IPlayer* player);
DLL_EXPORT bool Player_GetKickStatus(const IPlayer* player);
DLL_EXPORT void Player_ClearTasks(const IPlayer* player, PlayerAnimationSyncType syncType);
DLL_EXPORT void Player_AllowWeapons(const IPlayer* player, bool allow);
DLL_EXPORT bool Player_AreWeaponsAllowed(const IPlayer* player);
DLL_EXPORT void Player_AllowTeleport(const IPlayer* player, bool allow);
DLL_EXPORT bool Player_IsTeleportAllowed(const IPlayer* player);
DLL_EXPORT bool Player_IsUsingOfficialClient(const IPlayer* player);
